# A dockerfile to keep the protobuf-specs based builder up to date, we don't actually bulid from here
FROM ghcr.io/sigstore/protobuf-specs-service-builder:0.5.2@sha256:13d9b82a8f9b9271f7f81fabf251812495cfac3f4053a3ca6488120edbc49a5d
